---
title: "CARA MENJUAL BARANG DENGAN PENAWANRAN"
author: "Albani"
date: "2025-01-10"
categories: [Marketing, Bisnis, Menjual]
---
> *Menjual itu ada seninya...*

-------

NATARU, Natal dan Tahun baru. Merupakan puncak seasonal tahunan yang dijadikan ajang pengejaran sales bagi semua pengusaha. Teruma di kantor saya, setiap tahunnya kami selalu melakukan kunjungan toko guna perbantuan dalam event-event yang dijalankan tim Development. Giliran saya yang memilih ditempatkan di toko Fresh S. Parman. Sebelum melakukan kerjaan membantu dalam pelayanan dalam toko, tim toko bersama Supervisior mereka melakukan ritual penting (breafing).

Dalam pelaksanaan breafing saya mendapatkan banyak sekali masukan yang saya dapatkan. Yang saya dapatkan adalah sebagai berikut :
        
        "Setelah konsumen sudah di kasiran itu adalah senjata kita untuk mendapatkan sales, menawarkan yang sedang promo, yang lebih besar, yang lebih hemat dan barang lain pelengkap dengan yang dibeli konsumen".

Mendengar arahan breafing ini saya langsung teringat materi teknik selling yang diajarkan abang saya, Cross selling, Up Selling, dan Down Selling. Ayo kita bahas :

1. **Cross Selling**

Ini adalah teknik menjual barang dengan penawaran peran pendukung. Maksudnya bagaimana? Misal disuatu lorong atau rak dengan bagain food, kita sediakan alat seperti pisau atau talenan. Nah ini yang dinamakan cross selling. Pada POS kasir ini harus ada beberapa barang cross selling yang paling banyak orang beli. Disini dibutuhkan peran tim analis, mereka melakukan penyajian data penjualan mana saja yang sering orang beli. Dengan data historys tersebut kita bisa mengimpan belanjaan apa saja yang dibutuhkan. 

Misal, suatu data analis mendata bahwa dengan analisis pareto, 80% barang yang laku dengan tinggi di siang hari adalah sabun dan beberapa alat rumahan. Dan malam hari kebanyakan orang beli adalah kopi dan jenis makanan ringan.

Dengan mengetahui data historis dari tim data analys, kita bisa melakukan strategi barang apa yang kiranya dapat dijadikan sebagai bahan Cross seling tersebut.

> Tentu saja barang promosi wajib ditawarkan sebagai Up selling juga.

2. **Up Selling**

Selanjutnya adalah penawaran yang dilakukan jika barang yang dibeli konsumen ukuran medium atau small. Jika konsumen membelinya disini adalah target dari kasir kasir kita. Kasir bisa menawarkan penjualan berupa barang yang lebih besar dari barang awal. Dengan Up Selling juga, Kasir bisa menawarkan promosi beli lebih murah, atau dengan menawrkan produk langka sehingga bisa menjadi kreasi konsunmen untuk membeli banyak.

3. **Down Selling**

Selanjutnya adalah Down Selling, ini yang wajib dilakukan jika konsumen membeli barang dengan uang yang Pas. Jangan sampai konsumen keluar tanpa barang 1 pun dari toko. Misal konsumen membeli mangga madu, karena uang konsumen kurang maka kasir bisa inisiatif agar konsumen tidak keluar tangan kosong. Memberikan barang yang lebih murah misalnya. `"Bu silakan mangga macannya Bu ini mirip dengan mangga madu dan baunya lebih baik, Ibu bisa beli ini dengan harga yang lebih terjangkau"`.

Inilah ilmu menjual dari Abangku, ahahaha daging semua pembahasan saat ketemu dengan beliau. Okelah akhirnya tuntas juga menulis analisa harian saya. Hari ini analisa penjualan brang dan analisa marketing. See you on the next story.